#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        if [ -x "$(command -v systemctl)" ]; then
            # Stop and disable the service globally for all users
            systemctl --global disable openrgb-daemon.service || true
            systemctl --global stop openrgb-daemon.service || true
        fi
        ;;
        
    failed-upgrade)
        ;;
        
    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0